SISproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sisapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sisapp/urls.py
from django.urls import path
from . import views

app_name = 'sisapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('personalinfo/', views.personalinfo, name='personalinfo'),
    path('publishedres/', views.publishedres, name='publishedres'),
    path('personalacc/', views.personalacc, name='personalacc'),
    path('success/', views.success, name='success'),
    path('payments/', views.payments, name='payments'),
    path('message/', views.message, name='message'),
    path('upload_results/', views.uploadresults, name='uploadresults'),
    path('stdterm/', views.stdterm, name='stdterm'),
    path('saveresults/', views.saveresults, name='saveresults'),
    path('promote/', views.promote, name='promote'),
    path('savepayments/', views.savepayments, name='savepayments'),
]

sisapp/models.py
# from re import T
# from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.http.request import split_domain_port

# Create your models here.
class Guardian(models.Model):
    id = models.AutoField(primary_key=True)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    othername = models.CharField(max_length=255)
    fullname = models.CharField(max_length=255, null=True, default="")
    email = models.EmailField()
    profession = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    gps = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)

    def _str__(self):
        return self.fullname


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            username=username,
        )

        user.is_admin = True
        user.save(using=self._db)
        return user

GENDER = [('male','male'),
        ('female','female')]
StudentLevel = [('Basic 1','Basic 1'),
                ('Basic 2','Basic 2'),
                ('Basic 3','Basic 3'),
                ('Basic 4','Basic 4'),
                ('Basic 5','Basic 5'),
                ('Basic 6','Basic 6'),
                ('Basic 7','Basic 7'),
                ('Basic 8','Basic 8'),
                ('Basic 9','Basic 9')]

GROUP = [('A','A'),
        ('B','B'),
        ('C','C'),
        ('D','D')]
class MyUser(AbstractBaseUser):
    id = models.AutoField(primary_key=True)
    username = models.CharField(
        verbose_name='username',
        max_length=255,
        unique=True,
        null=True,
    )
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    firstname = models.CharField(
        verbose_name='firstname',
        max_length=255,
        null=True,
        unique=True
    )
    phone = models.CharField(
        verbose_name='mobile number',
        max_length=15,
        null=True,
    )
    # othername = models.CharField(
    #     verbose_name='othernames',
    #     max_length=255,
    #     null=True,
    #     blank=True,
    # )
    gender = models.CharField(
        verbose_name='gender',
        max_length=255,
        null=True, default='null',
        choices=GENDER,
    )
    date_of_birth = models.DateField(
        auto_now_add=True
    )
    group = models.CharField(
        max_length=2,
        null=True, choices=GROUP
    )
    level = models.CharField(
        max_length=10, null=True,
        choices=StudentLevel
    )
    yearOfadmission = models.CharField(
        max_length=10, null=True,
        default='null'
    )
    classAdmitted = models.CharField(
        max_length=10, null=True, choices=StudentLevel
    )
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    guardian = models.ForeignKey(Guardian, blank=True, null=True, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    def get_full_name(self):
        # The user is identified by their email address
        return self.firstname + " " + self.surname

    class Meta:
        verbose_name_plural = 'Users'


class Subject(models.Model):
    id = models.AutoField(primary_key=True)
    code = models.CharField(max_length=5, unique=True)
    title = models.CharField(max_length=20)
    period = models.IntegerField(default=20)
    # teacher = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title


LEVEL =[('Basic 1 Term 1','Basic 1 Term 1'),
        ('Basic 1 Term 2','Basic 1 Term 2'),
        ('Basic 1 Term 3','Basic 1 Term 3'),
        ('Basic 2 Term 1','Basic 2 Term 1'),
        ('Basic 2 Term 2','Basic 2 Term 2'),
        ('Basic 2 Term 3','Basic 2 Term 3'),
        ('Basic 3 Term 1','Basic 3 Term 1'),
        ('Basic 3 Term 2','Basic 3 Term 2'),
        ('Basic 3 Term 3','Basic 3 Term 3'),
        ('Basic 4 Term 1','Basic 4 Term 1'),
        ('Basic 4 Term 2','Basic 4 Term 2'),
        ('Basic 4 Term 3','Basic 4 Term 3'),
        ('Basic 5 Term 1','Basic 5 Term 1'),
        ('Basic 5 Term 2','Basic 5 Term 2'),
        ('Basic 5 Term 3','Basic 5 Term 3'),
        ('Basic 6 Term 1','Basic 6 Term 1'),
        ('Basic 6 Term 2','Basic 6 Term 2'),
        ('Basic 6 Term 3','Basic 6 Term 3'),
        ('Basic 7 Term 1','Basic 7 Term 1'),
        ('Basic 7 Term 2','Basic 7 Term 2'),
        ('Basic 7 Term 3','Basic 7 Term 3'),
        ('Basic 8 Term 1','Basic 8 Term 1'),
        ('Basic 8 Term 2','Basic 8 Term 2'),
        ('Basic 8 Term 3','Basic 8 Term 3'),
        ('Basic 9 Term 1','Basic 9 Term 1'),
        ('Basic 9 Term 2','Basic 9 Term 2'),
        ('Basic 9 Term 3','Basic 9 Term 3')]

# class Level(models.Model):
#     level = models.CharField(max_length=17, unique=True, null=True)

#     def __str__(self):
#         return str(self.level)

class Results(models.Model):
    id = models.AutoField(primary_key=True)
    subject = models.ForeignKey(Subject, null=True, on_delete=models.SET_NULL)
    student = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL)
    classScore = models.IntegerField()
    examscore = models.IntegerField()
    totalscore = models.IntegerField()
    position = models.CharField(max_length=10, null=True)
    level = models.CharField(max_length=17, null=False, blank=False)
    # term = models.IntegerField(default=1)

    class Meta:
        verbose_name_plural = 'Results'
        # ordering = ['-level']


class Final(models.Model):
    id = models.AutoField(primary_key=True)
    student = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    year = models.CharField(max_length=8)
    aggregate = models.FloatField(default=0.0)
    average = models.FloatField(default=0.0)


class Payment(models.Model):
    id = models.AutoField(primary_key=True)
    student = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    transaction_id = models.IntegerField()
    amount = models.FloatField()
    currency = models.CharField(max_length=5)
    date = models.DateTimeField(auto_now_add=True)
    flw_ref = models.CharField(max_length=20)
    tx_ref = models.CharField(max_length=20, default="hooli-tx-1920bbtyt")

    class Meta:
        verbose_name_plural = 'Payments'

    def __str__(self):
        return self.status

class Fees(models.Model):
    pass

sisapp/views.py
from django.http import request, JsonResponse
from django.shortcuts import redirect, render
from .models import Final, Guardian, LEVEL, MyUser, Payment, Results, Subject
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='loginform')
def index(request):
    return render(request, 'index.html')

@login_required(login_url='loginform')
def personalinfo(request):
    return render(request, 'personalinfo.html')

@login_required(login_url='loginform')
def publishedres(request):
    result = Results.objects.filter(student=request.user)
    level = Results.objects.values('level').distinct()
    str = "Basic 1 term 1"
    print(str[:7])
    context = {'results':result, 'levels':level}
    return render(request, 'publishedres.html', context)

@login_required(login_url='loginform')
def personalacc(request):
    return render(request, 'personalacc.html')

@login_required(login_url='loginform')
def success(request):
    return render(request, 'success.html')

@login_required(login_url='loginform')
def payments(request):
    return render(request, 'payment.html')

@login_required(login_url='loginform')
def message(request):
    users = MyUser.objects.filter(is_student = True)
    staffs = MyUser.objects.filter(is_teacher = True)
    print(users)
    context = {'users':users, 'staffs':staffs}
    return render(request, 'message.html', context)

@login_required(login_url='loginform')
def uploadresults(request):
    if request.method == 'POST':
        level = request.POST.get('levelselect')
        print(level)
        classlevel = level[:-7]
        print(classlevel)
        students = MyUser.objects.filter(is_student=True, level=classlevel)
        subjects = Subject.objects.all()
        context = {'students':students, 'level':level, 'subjects':subjects}
        return render(request, 'uploadresults.html', context)
    else:
        subjects = Subject.objects.all()
        return render(request, 'uploadresults.html', {'subjects':subjects})


@login_required(login_url='loginform')
def stdterm(request):
    
    if request.method == 'POST':
        level = request.POST.get('levelselect')
        results = Results.objects.raw(f'SELECT * FROM sisapp_myuser WHERE level="{level}" and is_student=1')
        res = Final.objects.all()
        context = {
            'results':results, 'res':res
        }
        return render(request, 'stdterm.html', context)
    else:
        return render(request, 'stdterm.html')


@login_required(login_url='loginform')
def submitresult(request):
    if request.method == 'POST':
        return redirect('sisapp:stdterm')


@login_required(login_url='loginform')
def saveresults(request):
    if request.method == 'POST':
        student = request.POST.get('student')
        classSore = request.POST.get('classSore')
        examscore = request.POST.get('examscore')
        totalScore = request.POST.get('totalScore')
        position = request.POST.get('position')
        subject = request.POST.get('subject')
        level = request.POST.get('level')
        # print(student," ", classSore," ", examscore," ", totalScore," ", position,
        # level," ", subject) 
        student = MyUser.objects.get(username=student)
        subject = Subject.objects.get(code=int(subject))
        res = Results.objects.filter(level=level, subject=subject, student=student)
        fin = Final.objects.filter(student=student, year=level[:-7])
        if fin:
            final = fin[0]
        else:
            final = Final(student=student, year=level[:-7], aggregate=0, average=0)
            final.save()
        if res:
            print(res)
            data = {'message': f"{student}'s result is already entered"}
            return JsonResponse(data)
        else:
            results = Results(student=student,subject=subject, classScore=classSore,
            examscore=examscore,totalscore=totalScore,position=position, level=level)
            results.save()
            agg1 = Final.objects.filter(student=student)[0]
            print(agg1)
            ag = agg1.aggregate
            print(ag)
            agg = float(ag) + float(totalScore)
            avg = (float(ag) + float(totalScore))/3
            Final.objects.filter(student=student).update(aggregate=agg, average=avg)
            data = {
                'message':'successfully saved',
                'student': f"{student}"
            }
            return JsonResponse(data)


@login_required(login_url='loginform')
def promote(request):
    if request.method == 'POST':
        student = request.POST.get('student')
        status = request.POST.get('status')
        if status == 'Promoted':
            level = MyUser.objects.get(firstname=student).level
            levelcls = level[6:]
            # print(levelcls)
            levelname = level[:-1] 
            # print(levelname)
            levelclsadd = int(levelcls) + 1
            # print(levelclsadd)
            newlevel = f"{levelname}{levelclsadd}"
            # print(newlevel)
            MyUser.objects.filter(firstname=student).update(level=newlevel)
            data = {
                'message':f'{student}'
            }
            return JsonResponse(data)
        else:
            data = {
                'message':f'{student}'
            }
            return JsonResponse(data)


def savepayments(request):
    if request.method == 'POST':
        amount = request.POST.get('amount')
        currency = request.POST.get('currency')
        student = request.POST.get('student')
        mobile = request.POST.get('mobile')
        flw_ref = request.POST.get('flw_ref')
        transaction_id = request.POST.get('transaction_id')
        student = MyUser.objects.get(firstname=student)
        pay = Payment(amount=amount, currency=currency, student=student,mobile=mobile, flw_ref=flw_ref, transaction_id=transaction_id)
        pay.save()
        print('successfully done')
        return redirect('sisapp:success')

sisapp/templates/index.html
{% extends 'base.html' %}	
{% load static %}
{% block index %}
	<!-- main body -->
	<div class="container">
		<div style="min-height: 25px;"></div>
		<div class="row">
			<div class="col-sm" id="left" >
				<h2 class="text-center">Welcome to the SIS {{request.user}}</h1>
				<p>SIS is aportal that will allow you to access your personal student information.</p>
				<p>All student information is private and protected by Law. Please make sure you log out
				when not in use. Student information is only available to the student, the parent and the
				school with a legal educational interest in a student. Do not share any information with others.
				Contact the schooll if you have any questions. </p>
			</div>
			
			<div class="col-sm" id="right">
				<h2 class="text-center">Notification</h1>
				<div class="card">
					<div class="card-body">
						<div class="list-group">
							<a href="#" class="list-group-item list-group-item-action" aria-current="true">
							  Cras justo odio
							</a>
							<a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
							<a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
							<a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
							<a href="#" class="list-group-item list-group-item-action disabled" tabindex="-1" aria-disabled="true">Vestibulum at eros</a>
						  </div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}
	
	<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script> -->
<!-- </body>
</html> -->

sisapp/templates/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>

  <form>
    <script src="https://checkout.flutterwave.com/v3.js"></script>
    <!-- <button type="button" onClick="makePayment()">Pay Now</button> -->
    
  </form>
  {% csrf_token %}
  <script>
    // console.log(parseInt("{{request.user.id}}"))
   
    makePayment()
    function makePayment() {
      FlutterwaveCheckout({
        public_key: "FLWPUBK-66106623098f258c4726fa3ea93bcf8e-X",
        tx_ref: "hooli-tx-1920bbtyt",
        amount: 1.00,
        currency: "GHS",
        country: "GH",
        payment_options: "card, mobilemoneyghana, ussd",
        redirect_url: "" ,// specified redirect URL
          // "https://callbacks.piedpiper.com/flutterwave.aspx?ismobile=34",
        meta: {
          consumer_id: parseInt("{{request.user.id}}"),
          consumer_mac: "92a3-912ba-1192a",
        },
        customer: {
          email: "{{request.user.email}}",
          phone_number: "08102909304",
          name: "{{request.user.username}}",
        },
        callback: function (data) {
          console.log(data);
          // console.log(data.amount)
          // console.log(data.currency)
          // console.log(data.customer.email)
          // console.log(data.customer.name)
          // console.log(data.customer.phone_number)
          // console.log(data.flw_ref)
          // console.log(data.transaction_id)
          // // console.log(data.tx_ref)
          // console.log(data.amount)
          console.log(data.status)
          if(data.status == 'successful'){
            $.ajax({
              url: "{% url 'sisapp:savepayments' %}",
              type: "POST",
              data: {
                amount: data.amount,
                currency: data.currency,
                student: data.customer,
                mobile: data.phone_number,
                flw_ref: data.flw_ref,
                transaction_id: data.transaction_id,
                csrfmiddletoken: $('input[name=csrfmiddlewaretoken]').val(),
              },
              dataType: 'json',
              success: function(response){
                
              }
            });
          }
        },
        onclose: function() {
          // close modal
          window.history.back();
        },
        customizations: {
          title: "App Sch",
          description: "Payment of school fees",
          logo: "https://assets.piedpiper.com/logo.png",
        },
      });
    }
  </script>

<!-- {
  "account_bank": "MTN",
  "account_number": "233542773934",
  "amount": 50,
  "narration": "New GHS momo transfer",
  "currency": "GHS",
  "reference": "new-ghs-momo-transfer",
  "beneficiary_name": "Kwame Adew"
} -->
</body>
</html>
  

sisapp/templates/personalinfo.html
{% extends 'base.html' %}
{% load static %}
{% block personalinfo %}
{% load my_filter %}

	<!-- main body -->
	<div style="min-height: 20px;"></div>
	<div class="container">
		<div class="row border">
			<h3 class="container-fluid" style="margin: 10px auto 10px 10px;">User Profile</h3>
		  	<div class="col-sm border-left">
				<div style="min-height: 10px;"></div>
				<div class="border imgdiv">
					<img class="emptyimg" src="/static/img/emptyimg.png"/>
				</div>
				<div style="min-height: 30px;"></div>
				<div>
					<p><label>Name: </label> {{request.user.firstname}}</p>
					{% if request.user.is_student == True %}<p><label>Class: </label> {{request.user.level|levelname}}</p>{% endif %}
					{% if request.user.is_student == True %}<p><label>Group: </label> {{request.user.group}}</p>{% endif %}
					{% if request.user.is_student == True %}<p id="age"><label>Age: </label> {{request.user.date_of_birth|calcage}} years</p>{% endif %}
					<p><label>Gender: </label> {{request.user.gender}}</p>
					{% if request.user.is_student == True %}<p><label>Year of admission: </label> {{request.user.yearOfadmission}}</p>{% endif %}
					{% if request.user.is_student == True %}<p><label>Class admitted: </label> {{request.user.classAdmitted|levelname}}</p>{% endif %}
				</div>
		  	</div>
		  
		  	<!-- <div class="col-sm"> -->
				<!-- <div style="min-height: 10px;"></div> -->
				<!-- <div class="space" style="min-height: 190px;"></div>
				<div class="parentInfo">
					<p><label>Name of parent/guardian:</label>{{request.user.guardian.firstname}}</p>
					<p><label>Email :</label>{{request.user.guardian.email}}</p>
					<p><label>Phone :</label>{{request.user.guardian.phone}}</p>
					<p><label>Profession :</label>{{request.user.guardian.profession}}</p>
					<p><label>Address :</label>{{request.user.guardian.address}}</p>
					<p><label>GPS :</label>{{request.user.guardian.gps}}</p>
				</div>
		  	</div> -->

	<script>
		var userdate = document.getElementById('age').childNodes[1].data
		var converted = new Date(converted)
		console.log(userdate)
	</script>
{% endblock %}

sisapp/templates/stdterm.html
{% extends 'base.html' %}
{% block stdterm %}
{% load my_filter %}
<div class="container">
    <form class="row" action="" method="POST" id="uploadform">
        {% csrf_token %}
        <div class="mb-3 col-md-6">
            <label for="exampleInputEmail1" class="form-label">Select level</label>
            <select id="levelselect" name="levelselect" class="form-select form-select-lg mb-3" aria-label=".form-select-lg example">
                <option selected>Open this select level</option>
                <option value="Basic 1">Primary 1</option>
                <option value="Basic 2">Primary 2</option>
                <option value="Basic 3">Primary 3</option>
                <option value="Basic 4">Primary 4</option>
                <option value="Basic 5">Primary 5</option>
                <option value="Basic 6">Primary 6</option>
                <option value="Basic 7">JHS 1</option>
                <option value="Basic 8">JHS 2</option>
                <option value="Basic 9">JHS 3</option>
            </select>
        </div>
    </form>
    
    <!-- Shop Cart Section Begin -->
    {% csrf_token %}
    <section class="shop-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shop__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th>Student</th>
                                    <th>Class</th>
                                    <th>Average</th>
                                    <th></th>
                                    <th>Status</th>
                                    <!-- <th></th> -->
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in results %}
                                <tr>
                                    <td class="cart__product__item">
                                        <div class="cart__product__item__title">
                                            <h6>{{user.firstname}}</h6>
                                        </div>
                                    </td>
                                    <td class="cart__product__item">
                                        <div class="">
                                            <!-- <input type="text" value="{{result.student.level}}"> -->
                                            <h6>{{user.level|levelname}}</h6>
                                        </div>
                                    </td>
                                    <td class="cart__product__item">
                                        <div class="">
                                            <h6>{% for re in res %}{% if re.student|to_string == user.firstname|to_string %}{{re.average}} {% endif %}{% endfor %}</h6>
                                        </div>
                                    </td>
                                    <td class="cart__product__item">
                                        <div class="">
                                            <!-- <input type="text"> -->
                                            <!-- <button class="btn btn-danger" type="button">Repeat</button> -->
                                        </div>
                                    </td>
                                    <td class="cart__product__item">
                                        <div class="">
                                            <!-- <input type="text"> -->
                                            {%for i in res %}{% if i.student|to_string == user.firstname|to_string %}{% if i.average > 100.0 %}
                                            <button class="btn btn-success" type="button">Promoted</button>
                                            {%else%}<button class="btn btn-danger" type="button">Repeated</button>
                                            {% endif %}{% endif %}{% endfor %}
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}   
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button id="promote" class="btn btn-primary" type="button">Proceed Promotions</button>
        </div>
    </section>
    <!-- Shop Cart Section End -->
</div>

<script>

    document.getElementById('levelselect').onchange = function(){
        console.log(document.getElementById('levelselect').value)
        document.getElementById('uploadform').submit()
    }
    console.log('{{level}}')
    if("{{level}}" == "None"){
        document.getElementById('levelselect').selectedIndex = 0;
    } else {
        document.getElementById('levelselect').value = "{{level}}";
    }

    document.getElementById('promote').onclick = function(){
        $('tbody tr').each(function(){
            var student = $(this)[0].firstElementChild.innerText
            var status = $(this)[0].cells[4].innerText
            console.log(student)
            console.log(status)
            if (status.toString() == 'Promoted'){
                $.ajax({
                    url: "{% url 'sisapp:promote' %}",
                    type: "POST",
                    data: {
                        student: student,
                        status: status,
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    },
                    dataType: 'json',
                    success: function(response){
                        $('tbody tr').each(function(){
                            if($(this)[0].firstElementChild.innerText.toString() == response.message.toString() || status.toString() == 'Repeated'){
                                $(this).remove();
                            }
                        });
                    }
                });
            }
        });
    }

</script>
{% endblock %}